apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-auth
  release: dev
namespace: dev
resources:
- ../../base
replicas:
- name: auth
  count: 3
images:
- name: crkushal7/auth
  newName: crkushal7/auth
  newTag: auth-main-5445f5dbbfbb0f37dfb1156d40b353ccab0389e4
configMapGenerator:
- envs:
  - .env
  name: auth-config
