apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      volumes:
        - name: demo-app-creds
          secret:
            secretName: dev-demo-app-secret

        - name: shared-volume
          emptyDir: {}

      initContainers:
        - name: busybox
          image: busybox
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          command: ["/bin/sh"]
          args: ["-c", "echo 'hello kuberenetes' > /shared/abc.txt"]

      containers:
        - name: demo-app
          image: crkushal7/demo-app
          imagePullPolicy: Always
          volumeMounts:
            - name: demo-app-creds
              mountPath: /data

            - name: shared-volume
              mountPath: /data2
          resources:
            limits:
              cpu: "300m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
          ports:
            - containerPort: 4000
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-demo-app-config-9hf47t2bdm
                  key: PORT
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: dev-demo-app-config-9hf47t2bdm
                  key: NAME
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: dev-demo-app-config-9hf47t2bdm
                  key: HOST
            - name: ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: dev-demo-app-config-9hf47t2bdm
                  key: ADMIN_URL
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: dev-demo-app-config-9hf47t2bdm
                  key: MONGO_DB_URI
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: dev-demo-app-secret
                  key: USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-demo-app-secret
                  key: PASSWORD
