apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: demo-app-service
  labels:
    name: demo-app-service
    service: demo-app-service

spec:
  selector:
    app: demo-app
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
  type: ClusterIP
