apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-virtual-service
spec:
  hosts:
    - 'app.auth.com'
  gateways:
    - istio-gateway
  http:
    - route:
        - destination:
            host: dev-auth-service.dev.svc.cluster.local
            port:
              number: 4000
