---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "mongodb-service"
    namespace: "dev"
    labels: 
      app: "mongo"
  spec: 
    ports: 
      - 
        name: "mongodb"
        port: 27017
        targetPort: 27017
    clusterIP: "None"
    selector: 
      app: "mongo"