apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-demo-app
  release: dev
namespace: dev
resources:
- ../../base
images:
- name: crkushal7/demo-app
  newName: crkushal7/demo-app
  newTag: demo-app-main-9b3f3939d1dd8befc48966c9434aaf746e035c03
configMapGenerator:
- envs:
  - .env
  name: demo-app-config
