apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-manager
  release: dev
namespace: dev
resources:
- ../../base
replicas:
- name: manager
  count: 4
images:
- name: crkushal7/manager
  newName: crkushal7/manager
  newTag: manager-main-0abfee6855dd5f0b11e623a4d57f6c74d5487b52
configMapGenerator:
- envs:
  - .env
  name: manager-config
