apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-manager
  release: dev
namespace: dev
resources:
- ../../base
replicas:
- count: 2
  name: manager
images:
- name: crkushal7/manager
  newName: crkushal7/manager
  newTag: manager-main-82943400b6fefc1613c29ee9b1498500cd5d75ff
configMapGenerator:
- envs:
  - .env
  name: manager-config
