apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-manager
  release: dev
namespace: dev
resources:
- ../../base
replicas:
- name: manager
  count: 3
images:
- name: crkushal7/manager
  newName: crkushal7/manager
  newTag: manager-main-5445f5dbbfbb0f37dfb1156d40b353ccab0389e4
configMapGenerator:
- envs:
  - .env
  name: manager-config
